### ISSUE TITLE
on panel closed event handler

### ISSUE THREAD

**Issue by ericsturman** [TeselaGen/tg-oss#103]
@tnrich

We would benefit from an on panel close event handler.  I can submit a pull request if there are no objections.

Eric

**Comment by tnrich** [comment]
@ericsturman  You're talking about when a tab panel is closed? Sure I see no reason why not to have one!

**Comment by ericsturman** [comment]
@tnrich yes, when a tab panel is closed... Thanks!

**Comment by tnrich** [comment]
@ericsturman did this one get finished?

**Comment by ericsturman** [comment]
@tnrich yes.

**Comment by tnrich** [comment]
Thx!
