### ISSUE TITLE
RowView can not set width props

### ISSUE THREAD

**Issue by hi-asan** [TeselaGen/tg-oss#12]
![image](https://github.com/TeselaGen/tg-oss/assets/12293038/52e97589-b402-4b1c-bcd5-7bdb546c1f17)
![image](https://github.com/TeselaGen/tg-oss/assets/12293038/17f29e82-668c-480d-b6ef-b015e55db953)
<img width="678" alt="image" src="https://github.com/TeselaGen/tg-oss/assets/12293038/d69c863a-4d0d-4695-bbd8-baea6fbb078e">

No matter how it is set, the width will always be defaultContainerWidth. cannot cover

**Comment by tnrich** [comment]
@hi-asan doing this will work for ya - 

`dimensions={{width: 800}}`

<img width="612" alt="image" src="https://github.com/TeselaGen/tg-oss/assets/2730609/6d88e240-1532-434c-a025-3fe3daacf0ef">

<img width="877" alt="image" src="https://github.com/TeselaGen/tg-oss/assets/2730609/8b8d171e-c475-487e-aa19-066c740ca558">

**Comment by tnrich** [comment]
@hi-asan  lemme know if the above does it for ya. Closing

**Comment by hi-asan** [comment]
Yes, the problem has been resolved. Thank you very much. I plan to adjust the changes I made in the source code back
