### ISSUE TITLE
Project/Folder navigation

### ISSUE THREAD

**Issue by jmarlhens** [TeselaGen/tg-oss#17]
Dear @tnrich, dear all,

I really like the software. The graphics and simple interface are one of the best I've tried.
One thing that may be missing is a navigation window or visual so I can switch sequences fast. Do you know if it is available or if you are planning to add it.

Regards, Jeremie

**Comment by tnrich** [comment]
@jmarlhens that isn't a feature I've really considered. In what context are you using ove? 

Thanks

**Comment by jmarlhens** [comment]
@tnrich in many of my projects, I work with multiple plasmids, and I've found that quick navigation between them is essential. A functionality like SnapGene's, where I can open and close them in separate windows without having to go through the menu each time, is really nice.

**Comment by tnrich** [comment]
@jmarlhens thanks for responding, are you using ove through ove-electron? Or thru teselagen? Or through something else? The demo page of ove isn't really meant to be a standalone tool. A windowing solution is probably more suited to be implemented in one of those parent applications

**Comment by tnrich** [comment]
Closing for now. @jmarlhens please feel free to respond still
