### ISSUE TITLE
ReadOnly mode callback

### ISSUE THREAD

**Issue by wandji20** [TeselaGen/tg-oss#19]
@tnrich, I have an OVE integration that runs smoothly so far.
However, I would like to react to changes in our application when the readOnly mode is toggled.
Just wondering if this feature already exists, or would be a nice first issue for me?
Thanks

**Comment by tnrich** [comment]
Hi @wandji20 I don't believe I have an onReachOnlyChanged handler set up yet, I'll look into this and get back to you.

**Comment by tnrich** [comment]
Hi @wandji20 I've added a new handler called  `beforeReadOnlyChange` that should allow you to react to changes to readOnly as well as prevent those changes (if necessary) by returning `false` from the handler (can be async if necessary).

These changes landed in @teselagen/ove v0.3.13

**Comment by tnrich** [comment]
Lemme know if you need anything else!

**Comment by wandji20** [comment]
Hi @tnrich
Thank you so much for making this change!
So we are integrating OVE into our product via CDN and I can't find the **beforeReadOnly** handler in the CDN yet.
I am not sure if I am checking correctly, but I would love to confirm if it is already available via the CDN.
Thanks

**Comment by tnrich** [comment]
Can you be a bit more specific about which CDN you're using @wandji20 ?

**Comment by wandji20** [comment]
Sure @tnrich
I did check with this CDN **https://unpkg.com/open-vector-editor/umd/main.css**
Also, checked my node-modules/open-vector-editor/umd/open-vector-editor.js after installing via npm.

**Comment by wandji20** [comment]
Hi @tnrich 
Found the change here https://www.npmjs.com/package/@teselagen/ove.
Probably, I was not checking in the right place.
Thank you so much
