### ISSUE TITLE
【bug】Accidentally exceeding the sequence range may cause the browser to freeze

### ISSUE THREAD

**Issue by hi-asan** [TeselaGen/tg-oss#22]
![image](https://github.com/TeselaGen/tg-oss/assets/12293038/4e0e0043-953d-4865-9d35-c90a4cf14077)

Reproducible in demo

@tnrich

**Comment by tnrich** [comment]
Thanks @hi-asan I'll look into this!

**Comment by tnrich** [comment]
@hi-asan fixed in @teselagen/ove  v0.3.14
