### ISSUE TITLE
Browser console error when opening editor with empty sequence content.

### ISSUE THREAD

**Issue by wandji20** [TeselaGen/tg-oss#28]
Hi @tnrich
There is a browser console when launching the editor without a sequence value for sequenceData attribute. ie `sequenceData: { ...otherProps, sequence: '', },`
I must explicitly set a sequence value eg ` sequence: '1',` to clear the console errors.
Would there be another approach to clear such errors since we would rather have the user open a completely empty editor when trying to create a new sequence?
Thanks

**Comment by tnrich** [comment]
Hi @wandji20 I've published a new version that maybe rids the console of some of the errors you're seeing. Wanna try out the latest OVE and lemme know if you're still seeing issues? If you are please paste some screenshots of what you're seeing here!

**Comment by wandji20** [comment]
Thanks @tnrich 
The errors are now cleared
What I get no is a warning about using createRoot with React!
Here is a screenshot of my browser console
![image](https://github.com/TeselaGen/tg-oss/assets/65476715/4b2dff39-3163-4548-b143-9ce37904feec)

**Comment by tnrich** [comment]
Hi @wandji20 those errors should go away when we upgrade to blueprint v4 but we're a ways out from being able to do that. 

<img width="562" alt="image" src="https://github.com/TeselaGen/tg-oss/assets/2730609/3c403386-afd5-4c48-92d5-1735a88d99e3">

**Comment by tnrich** [comment]
@wandji20 it looks like the upgrade to react v18 will be delayed a bit longer, at least until https://github.com/react-grid-layout/react-draggable/issues/698 is fixed

**Comment by wandji20** [comment]
Thanks @tnrich
