### ISSUE TITLE
Need some help with setting up the alignment tool

### ISSUE THREAD

**Issue by acostin** [TeselaGen/tg-oss#29]
@tnrich I'm using the open vector editor and it is great! Using it inside a vue app and all is good so far. I've been using the demo page (https://teselagen.github.io/tg-oss/ove/#/Editor) to play around with all the features and see how to use them etc. I now need to set up sequence alignment and not sure where to begin. The demo mentions that I need to hook up an alignment server, but not sure what all of that entails. Is it just an event that I need to hook into when the "Create Alignment" button is clicked then I can throw it to my custom logic? How have you seen it be done? There's not that much detail in the readme/docs that I could see about this, are there any concrete examples out there? All I need to do is to align another sequence to the one that is in the editor already.

Thanks, appreciate your great work!

**Comment by tnrich** [comment]
Hi @acostin , you'll have to implement your own alignment functionality. 

I made the demo simpler for you and other people that have had similar questions about how to do this: 

<img width="600" alt="image" src="https://github.com/TeselaGen/tg-oss/assets/2730609/1c1419db-49f4-4a7c-8aba-4a69cf8353e6">

The demo can be seen here: 
https://teselagen.github.io/tg-oss/ove/#/

And the source code for that simple alignment is in tg-oss/packages/ove/demo/src/EditorDemo/index.js

Hope that helps!

**Comment by acostin** [comment]
Thank you! This is helpful for sure.

**Comment by tnrich** [comment]
Ok closing this then. Feel free to ask more questions
