### ISSUE TITLE
contributing.md

### ISSUE THREAD

**Issue by manulera** [TeselaGen/tg-oss#34]
Hello @tnrich,

I made a small PR to contribute to #32, but I would have struggled to make a more significant contribution, as I am not very familiar with javascript packaging. I think it would be very helpful to include a `contributing.md` document explaining how to install the dependencies and how to add and run tests in the different packages.

**Comment by tnrich** [comment]
@manulera good idea. I've added a CONTRIBUTING.md file to the repo. Let me know if that solves this for you
