### ISSUE TITLE
OVE not updated?

### ISSUE THREAD

**Issue by jobabi** [TeselaGen/tg-oss#40]
Dear Thomas,
it seems that the update of this calculation problem:
[https://github.com/TeselaGen/openVectorEditor/issues/916]
has been not updated.
When I used this link
[https://teselagen.github.io/openVectorEditor/#/Editor]
I still get the wrong mass for the translation

best wishes 
Jochen

@tnrich

**Comment by tnrich** [comment]
Hi @jobabi the new demo link for ove is - https://teselagen.github.io/tg-oss/ove/#/Editor

I'll take down the old link. Thanks!

**Comment by tnrich** [comment]
Closing this but feel free to ask other questions! And don't forget to star the new repo ;)
