### ISSUE TITLE
Unexpected token (40059:10) in @teselagen/ui/index.es.js

### ISSUE THREAD

**Issue by nicolazilio** [TeselaGen/tg-oss#42]
Hello @tnrich,

I've been trying to merge your latest changes to the OVE demo into my fork https://github.com/helle-ulrich-lab/ove-plasmid-viewer but when I try to build the app, I get the following error

```
[commonjs--resolver] Unexpected token (40059:10) in /home/xxx/dev_ove/node_modules/@teselagen/ui/index.es.js
file: /home/xxx/dev_ove/node_modules/@teselagen/ui/index.es.js:40059:10
40057:         return __spreadValues({
40058:           key: id2,
40059:           {}: props.global !== false,
                 ^
40060:           onKeyDown: function(e2) {
40061:             return handlers2[id2](e2);
```

Any ideas why?

Thanks in advance!

**Comment by tnrich** [comment]
Hi @nicolazilio I'm not sure what might be causing that.. I can look into it real quick

**Comment by tnrich** [comment]
Hi @nicolazilio this is basically being caused by a difference in how vite/webpack handle the polyfilling of the `global` object. I had tried to work around vite NOT adding the global polyfill by adding this line in the vite config: 

![Uploading image.png…]()

**Comment by tnrich** [comment]
@nicolazilio it appears that you'll need to add that shim for the global object yourself to your project. You can see how I do it here: 

https://github.com/tnrich/ove-react-demo-repo

**Comment by nicolazilio** [comment]
Worked like a charm, thanks!
