### ISSUE TITLE
Error when right-clicking feature with editing enabled and parts disabled

### ISSUE THREAD

**Issue by ryan-stackwave** [TeselaGen/tg-oss#58]
With editing enabled and parts disabled via `updateEditor`, an error is thrown if you right-click a feature.
```
editor.updateEditor({
    annotationsToSupport: {
        parts: false,
    }
});
```
https://jsfiddle.net/zah72dnm/3/

@tnrich

**Comment by tnrich** [comment]
@ryan-stackwave thank you for the js-fiddle but I can't seem to reproduce the error you're seeing: 

<img width="1433" alt="image" src="https://github.com/TeselaGen/tg-oss/assets/2730609/0c71efa6-d33b-4983-b7e2-e65417a9ced4">

That's what happens for me when I right-click the feature. Do you see something different?

**Comment by ryan-stackwave** [comment]
@tnrich in order to see the error you first have to click the lock to enable editing.

**Comment by tnrich** [comment]
@ryan-stackwave thanks, publishing a new version of ove now for ya! Good catch and a big thanks on making the fiddle!
