### ISSUE TITLE
Double and Teselagen.bio.orf.ORF types for sequence-utils don’t exist

### ISSUE THREAD

**Issue by ryan-stackwave** [TeselaGen/tg-oss#59]
We get the following errors when importing from @teselagen/sequence-utils:

```
node_modules\@teselagen\sequence-utils\calculateTm.d.ts(1,102): error TS2304: Build:Cannot find name 'Double'. 

node_modules\@teselagen\sequence-utils\findOrfsInPlasmid.d.ts(1,129): error TS2503: Build:Cannot find namespace 'Teselagen'. 
```

The types seem to be generated from these comments:
https://github.com/TeselaGen/tg-oss/blob/master/packages/sequence-utils/src/getOrfsFromSequence.js#L11
https://github.com/TeselaGen/tg-oss/blob/master/packages/sequence-utils/src/calculateTm.js#L21

We were able to work around the error by defining global types:

```
declare namespace Teselagen {
   namespace bio {
       namespace orf {
           type ORF = string;
       }
   }
}

type Double = number;
```

@tnrich

**Comment by tnrich** [comment]
@ryan-stackwave hmm.. not sure why those comments are in there like that. Cleaned them up to hopefully prevent this issue for you and published a new version of @teselagen/sequence-utils

**Comment by tnrich** [comment]
Closing, reopen if necessary
