### ISSUE TITLE
ove tippy styles override those defined via tippy theme

### ISSUE THREAD

**Issue by ryan-stackwave** [TeselaGen/tg-oss#60]
Tippy styles for ove need to be defined with a narrower scope as they are overriding the base tippy styles and breaking the ability to use themes:

https://github.com/TeselaGen/tg-oss/blob/bd9119527e5cd7d6e9736747a24b85bb25482df1/packages/ui/src/style.css#L176

@tnrich

**Comment by tnrich** [comment]
What CSS are you trying to apply @ryan-stackwave? Also do you have a recommended fix for this codebase? 

Thanks!

**Comment by tnrich** [comment]
@ryan-stackwave bump :)

**Comment by ryan-stackwave** [comment]
Sorry @tnrich, got caught up with other things. Here's a jsfiddle demonstrating the issue:
https://jsfiddle.net/6qd3owpt/

I think we would probably be best served by creating a tippy theme for this project to narrow the scope of these styles to the tippy instances used inside this project. Want me to take a crack?

**Comment by tnrich** [comment]
Sure! Basically anything that allows us to keep the tippy styles looking like they currently do within our project should be fine! Thanks for looking into this!
