### ISSUE TITLE
When both AA and DNA are available, allow the user to choose which to export to FASTA

### ISSUE THREAD

**Issue by ryan-stackwave** [TeselaGen/tg-oss#61]
When reviewing a protein sequence it would be helpful for the user to be able to choose whether to export the AA or DNA to FASTA.

@tnrich

**Comment by tnrich** [comment]
@ryan-stackwave love these, keep em coming :)

**Comment by ryan-stackwave** [comment]
@tnrich, I can give this one a shot if it'd be helpful.

**Comment by tnrich** [comment]
Ya go for it! Would def be helpful :)
