### ISSUE TITLE
Error when clicking "+ Add Note" when creating a new feature

### ISSUE THREAD

**Issue by ryan-stackwave** [TeselaGen/tg-oss#63]
The error is: ResizeObserver loop completed with undelivered notifications.

To reproduce:
Enable editing -> Highlight sequence -> Right-click -> Create -> New Feature -> + Add Note

https://jsfiddle.net/zah72dnm/3/

@tnrich

**Comment by tnrich** [comment]
I can't seem to reproduce @ryan-stackwave : 

<img width="1440" alt="image" src="https://github.com/TeselaGen/tg-oss/assets/2730609/d0d99c61-8b70-4aba-9d70-98771220008b">

not sure why?

Can you send a video of you triggering it maybe?

**Comment by ryan-stackwave** [comment]
@tnrich it doesn't seem to error if the "New Feature" modal already has a vertical scrollbar so try giving yourself enough vertical window for the entire modal to display.

**Comment by tnrich** [comment]
Hmm @ryan-stackwave I tried again with no scrollbar and still couldn't get the error to occur I don't think: 

<img width="1439" alt="image" src="https://github.com/TeselaGen/tg-oss/assets/2730609/3469316c-0c88-481b-81da-84b40f386cb1">

Thoughts?

**Comment by ryan-stackwave** [comment]
@tnrich very strange, it's happening for me in both firefox and chrome:
![image](https://github.com/TeselaGen/tg-oss/assets/5443760/3bdacc34-d218-41e5-9b85-96776e6cb263)

**Comment by tnrich** [comment]
Is this breaking anything for you @ryan-stackwave or just showing up as an error?

**Comment by ryan-stackwave** [comment]
@tnrich this came up in our testing because we popup a message to the user whenever there are javascript errors. However, I can probably swallow any errors that come out of ove as a workaround.

**Comment by tnrich** [comment]
@ryan-stackwave I wouldn't swallow all the ove errors but this might be one of the ones you'll need to..

**Comment by ryan-stackwave** [comment]
@tnrich Debouncing the ResizeObserver callback seems to resolve the issue. Please let me know if you think that's a reasonable approach.
https://github.com/TeselaGen/tg-oss/pull/65
