### ISSUE TITLE
OVE - display correct aminoacid sequence in CDS with introns

### ISSUE THREAD

**Issue by manulera** [TeselaGen/tg-oss#69]
Hi @tnrich, it would be great if the aminoacid sequences in CDSs would account for introns. For example, in the following sequence from genbank ([ase1.txt](https://github.com/TeselaGen/tg-oss/files/15274436/ase1.txt)) there is a CDS with an intron:

```
     CDS             join(1174..1597,1645..3416)
                     /label="ase1"
                     /locus_tag="SPOM_SPAPB1A10.09"
```

It would be nice if this was accounted for in the displayed aminoacid sequence:

<img width="615" alt="Screenshot 2024-05-10 at 12 21 59" src="https://github.com/TeselaGen/tg-oss/assets/22526102/5e10951e-1da3-4026-82a4-c99c17d8b7c6">

For reference, this is how it looks in SnapGene and Benchling.
<img width="413" alt="Screenshot 2024-05-10 at 12 23 28" src="https://github.com/TeselaGen/tg-oss/assets/22526102/3e7d7175-9c35-4de2-8959-86eee06347e1">
<img width="468" alt="Screenshot 2024-05-10 at 12 22 15" src="https://github.com/TeselaGen/tg-oss/assets/22526102/010fa3fd-281c-4fc1-8ef6-b2fda2435ed7">

Happy to propose a fix via PR if you point me to the right place!

**Comment by manulera** [comment]
Hi @tnrich any thoughts on this and #70? As I said, I would be happy to make a PR if you point me on where to start

**Comment by tnrich** [comment]
Hi @manulera sorry for the delay. Yes I think this could be a good one for you to try to tackle if you'd like! You'll basically need to look into the Translations /index.js file and see if you can update the rendering to leave out the appropriate joins

<img width="737" alt="image" src="https://github.com/TeselaGen/tg-oss/assets/2730609/46511eed-42cd-4952-af4f-ea8d2e74f2f9">

The feature appears to be drawing based on the "locations" array being passed to it. I think a similar logic will need to be added for the AA to be drawn based on the locations array and not the start/end of the AA range. 

Might also need to do some logic around here: 
<img width="565" alt="image" src="https://github.com/TeselaGen/tg-oss/assets/2730609/1c46ff23-b7fe-4c8f-99e1-95d35ea1f6fc">

I think just splitting the translation into multiple pieces for the different locations shouldn't be too tough, the tricky part will be getting the translation to be continuous across the joins and not "restart" for each location. 

Good luck and let me know how it goes! 😄

**Comment by tnrich** [comment]
Closing as this has been merged and published! Lemme know if it works for you @manulera !

**Comment by manulera** [comment]
Amazing! Thank you so much. This is quite important when displaying genomic sequences.

There were couple of questions in https://github.com/TeselaGen/tg-oss/pull/76#issue-2333200855 in the "Unrelated to the implementation" section, in case you want to have a look. They are not important for my use-case, but I think they could lead to bugs in the future.
