### ISSUE TITLE
OVE - feature strand not correctly displayed in SimpleCircularOrLinearView

### ISSUE THREAD

**Issue by manulera** [TeselaGen/tg-oss#70]
Hi @tnrich, I noticed that the `SimpleCircularOrLinearView` editors always display the feature as if it was in the reverse strand, regardless of the `feature.strand` attribute.

You can check this in [this repo](https://github.com/manulera/ove_playground)

Also, I made a video of it. An app that changes the strand of the feature, and you can see the main editor changes, but not the `SimpleCircularOrLinearView`.

Happy to provide a fix via PR if you point me somewhere.

https://github.com/TeselaGen/tg-oss/assets/22526102/3f604f06-ce40-4b8e-bc62-e3d62325ba22

**Comment by tnrich** [comment]
Hi @manulera you can set `forward: true,` for a feature/part and have it display in the forward orientation. That should fix this for you. I'll add an example to the `SimpleCircularOrLinearView` demo

**Comment by manulera** [comment]
Hi @tnrich, thanks that makes it work for me as well.

However, why is this needed only for `SimpleCircularOrLinearView`? When I use `createVectorEditor`, setting `strand` in the features is enough for them to render in the right orientation. Also, when reading a file from genbank format, this `forward` attribute does not seem to be set either, perhaps something to do with the feature parser then?

What is the reason for not using `strand` in `SimpleCircularOrLinearView`?

**Comment by tnrich** [comment]
Hi @manulera probably because the `createVectorEditor` runs the `sequenceData` through the `tidyUpSequenceData` function whereas the `SimpleCircularOrLinearView` does not do that..? Perhaps we should investigate running the `sequenceData` passed to the `SimpleCircularOrLinearView` thru the same `tidyUpSequenceData` function?

**Comment by manulera** [comment]
Hi @tnrich, yes that worked, thank you! Do you think `tidyUpSequenceData` should be called by `convertToTeselaJson` by default before returning the result?

**Comment by manulera** [comment]
Also, now the sequences look so much better! Is there some docs on the difference between the input and output?

Before
<img width="307" alt="Screenshot 2024-05-24 at 11 42 47" src="https://github.com/TeselaGen/tg-oss/assets/22526102/272167ce-b1d8-446d-8c29-d6dacb712284">

After
<img width="251" alt="Screenshot 2024-05-24 at 11 42 43" src="https://github.com/TeselaGen/tg-oss/assets/22526102/d6afbb1b-968e-495b-8e84-0b4ab16188e3">

**Comment by tnrich** [comment]
@manulera where is the `convertToTeselaJson` function you're asking about? 

I'm not sold on adding the tidyUpSequenceData step directly to SimpleCircularOrLinear view since I don't want that conversion to be run more than is necessary.

**Comment by manulera** [comment]
Hi @tnrich, I have made a minimal example that you can test in https://ove-playground.netlify.app/

Essentially, using the bottoms at the top, you can:

* switch the strand in a feture read from a genbank string using `genbankToJson`, and the sequence is displayed  both `SimpleCircularOrLinearView` and using `createVectorEditor`.
* Optionally choose if `tidyUpSequenceData` is applied or not to the sequence read from the genbank string.

All this is in [this very short component](https://github.com/manulera/ove_playground/blob/master/src/EditorComparison.jsx).

As you can see, when reading a sequence using `genbankToJson`:
* In the `creteVectorEditor`, it does not matter if you call `tidyUpSequenceData`, the strand of the feature is displayed correctly in both cases.
* In the `SimpleCircularOrLinearView`, you have to call `tidyUpSequenceData` for the strand of the feature to be displayed properly.

Should I using another function that runs this post-processing instead of `genbankToJson`?

**Comment by tnrich** [comment]
@manulera thanks for catching this. I've updated the genbankToJson to output the .forward property as well. Let me know if the latest release fixes this for you.

**Comment by manulera** [comment]
Hi @tnrich I updated to the last version of bio-parsers, and as you can see the problem persists (I still have to call `tidyUpSequenceData`) when using `SimpleCircularOrLinearView `.

See the demo app here: https://ove-playground.netlify.app/

Also, as mentioned above the features are still displayed differently in the UI when you call or not call tidyUp

**Comment by tnrich** [comment]
@manulera seems to work for me off the master branch - https://github.com/TeselaGen/tg-oss/compare/tnwTestEdComparison

**Comment by manulera** [comment]
I see, that works for me as well, I was just changing `strand` in my code when the button was clicked, and I had to change `forward` as well. I have changed that in the playground example and now it reverts the feature in the display. Sorry about that.

However, the displayed sequence still looks much better if using `tidyUpSequenceData` in the `SimpleCircularOrLinearView `, but in the main editor it always looks well. Should this be the case?

With tidyUp

<img width="163" alt="Screenshot 2024-06-05 at 20 54 24" src="https://github.com/TeselaGen/tg-oss/assets/22526102/587a6e53-214b-4be6-8d96-d038d4dab701">

<img width="233" alt="Screenshot 2024-06-05 at 20 54 07" src="https://github.com/TeselaGen/tg-oss/assets/22526102/30819101-c93f-493d-a776-a6dd610e3811">

Without tidyUp. All features are shown in purple regardless of type in circular, and names overlap in both linear and circular

<img width="167" alt="Screenshot 2024-06-05 at 20 54 20" src="https://github.com/TeselaGen/tg-oss/assets/22526102/d54a588a-749f-451b-a961-89f57b1b0f78">
<img width="238" alt="Screenshot 2024-06-05 at 20 54 11" src="https://github.com/TeselaGen/tg-oss/assets/22526102/4fd72565-d123-4806-8d01-5f3ffead29e7">

You can test again here: https://ove-playground.netlify.app/

**Comment by manulera** [comment]
Alright, will do that!

**Comment by tnrich** [comment]
Thanks! Appreciate all the work you're doing!
