### ISSUE TITLE
Missing LICENSE information in packages

### ISSUE THREAD

**Issue by NicolasCARPi** [TeselaGen/tg-oss#8]
Hello,

My license scanning tool cannot find the license of the sub-packages:

![2023-07-28-013443_1279x512_scrot](https://github.com/TeselaGen/tg-oss/assets/3043706/d54ffe8c-35e7-482a-b003-24205b596bbf)

I suggest adding a:

~~~json
"license" : "MIT",
~~~

to all the `package.json` that live under the `packages` folder, so it can be found in the npm published code.

**Comment by tnrich** [comment]
@NicolasCARPi publishing new versions now that should have `"license" : "MIT",` in their package jsons

**Comment by NicolasCARPi** [comment]
Great, thanks! :rocket:
