### ISSUE TITLE
Cut sites are displayed in the wrong place when shown in specific enzyme information

### ISSUE THREAD

**Issue by eric-bra** [TeselaGen/tg-oss#80]
@tnrich
When opening the information about an enzyme, the lines symbolizing the cut site are shifted to the right.
In the Cut site graphic in properties/cut sites, when a specific enzyme is selected, there is also a shift.
The bug was found in the demo and not verified building the project myself.

Correct line in Sequence Map:
<img width="71" alt="Bildschirmfoto 2024-06-27 um 14 11 06" src="https://github.com/TeselaGen/tg-oss/assets/83550924/acd97a9b-6572-4704-a2b0-d0654ea5f3b6">

Enzyme Information (Pop-up):
<img width="387" alt="View in enzyme overview" src="https://github.com/TeselaGen/tg-oss/assets/83550924/25d156b2-384e-4c42-8ed3-f9a7a484dabd">

Enzyme Information (Properties):
<img width="578" alt="Bildschirmfoto 2024-06-27 um 14 10 56" src="https://github.com/TeselaGen/tg-oss/assets/83550924/f7cd1023-3127-4b17-81e4-267e3e72284e">

**Comment by tnrich** [comment]
@eric-bra yikes thanks for making an issue! I'll look into this.

**Comment by tnrich** [comment]
@eric-bra I don't think I can reproduce this.. This is what I see on the demo page here - https://teselagen.github.io/tg-oss/ove/#/Editor

<img width="1438" alt="image" src="https://github.com/TeselaGen/tg-oss/assets/2730609/84ceb1a4-6d00-4829-9884-2fff13928d9b">



Can you provide additional reproduction assistance?

**Comment by eric-bra** [comment]
I found the original bug in Safari Version 17.5 (19618.2.12.11.6) on an up-to-date intel-based Mac, I was able to recreate it on an up-to-date iPad in both safari and Firefox, but not on my mac in firefox.

**Comment by tnrich** [comment]
@eric-bra thanks for the additional info. I can see this on Safari on mac as well. It appears to be an issue with safari's handling of the textLength attribute. I think I can add a safari specific fix that changes how the text is handled and fix this issue. 

Cheers!

**Comment by tnrich** [comment]
Closing as fixed
