### ISSUE TITLE
OVE: Display not fully-matching primers

### ISSUE THREAD

**Issue by manulera** [TeselaGen/tg-oss#84]
Hi @tnrich, hope things are going well!

I think it would be quite nice to be able to display primers that don't fully overlap with the sequence. For instance, primers that have a tail at their 3' end or some mismatches. This is how they are displayed in SnapGene:

<img width="760" alt="Screenshot 2024-07-10 at 10 06 34" src="https://github.com/TeselaGen/tg-oss/assets/22526102/1c2e9cc6-00be-442d-9950-153c643b25b2">

I am thinking that in a `primer_bind` feature, one could add a `\sequence` qualifier with the primer sequence, and use that for the display.

The top case (assuming no mistmaches) is the easiest, because it would be just adding a tail behind the feature. I don't think it's necessary that the tail length is proportional, nor that it includes the sequence. If it's short maybe?

The other one is a bit more tricky, since it would be nice to position the insertions / changes on the right position of the sequence. It could be done with a `*` symbol or with the actual letters, but that would be a bit more complicated if there are insertions, etc.

I don't know how feasible/hard this is, but if you think it makes sense and you point me to the place in the library like last time, I can give it a go.

**Comment by tnrich** [comment]
@manulera I believe this is already implemented: 
<img width="1440" alt="image" src="https://github.com/TeselaGen/tg-oss/assets/2730609/abc940c9-adda-483d-a8a1-99d576678d0e">

See here - 
https://teselagen.github.io/tg-oss/ove/#/Editor?searchInput=primer&allowPrimerBasesToBeEdited=true

Lemme know if that is what you're looking for..

**Comment by manulera** [comment]
Oh! Amazing! Thanks

**Comment by manulera** [comment]
Got it working, thank you!
