### ISSUE TITLE
OVE: Disabling keyboard shortcuts

### ISSUE THREAD

**Issue by manulera** [TeselaGen/tg-oss#86]
Hi @tnrich, is there a way to disable the keyboard shortcuts? As in, a way to prevent the overriding of things like `ctrl+P`, etc. I believe in the library you call them "keycombos". I looked around but I could not see an obvious place to disable them.

**Comment by tnrich** [comment]
Hi @manulera I added a `massageCmds` prop to OVE: 


It can be used like so: 
```
                massageCmds={cmds => {
                  delete cmds.print.hotkey;
                  return cmds;
                }}
```

It also is on the demo page.

Lemme know if that does the trick for ya.

**Comment by manulera** [comment]
Thanks! Worked perfectly!
