### ISSUE TITLE
features with multiple sets of coordinates not rendering correctly when sequence is reverse complemented

### ISSUE THREAD

**Issue by ericsturman** [TeselaGen/tg-oss#95]
@tnrich

There appears to be a rendering issue when a feature like `araC` in the demo has its sequence reverse complemented.  If all of the sequence of the default demo vector is selected and reverse complemented, the extremes of the coordinates of `araC` are reverse complemented correctly as a skinny feature, but the fatter parts of the feature only have their orientations flipped and no change in coordinates.

before:
![1](https://github.com/user-attachments/assets/018cd4a5-50e5-4db7-bb87-1a28263b9367)

after:
![2](https://github.com/user-attachments/assets/345e85f4-20ff-47f5-8812-279b7a09767c)

**Comment by tnrich** [comment]
Uh oh that looks like a bug! Thanks for reporting it @ericsturman

**Comment by tnrich** [comment]
Published a fix @ericsturman. Thanks for the report!

**Comment by ericsturman** [comment]
Thanks for doing this so quickly @tnrich .  I have a question about the doubleclick event on features.  We use a custom set of feature types and when we doubleclick them we get a white screen and an error that gets thrown regarding `Objects are not valid as a React child (found: object with keys {key, value}). If you meant to render a collection of children, use and array instead.`.  I've tried to take a look at it but there is a lot to unpack.  There is also an error saying that it can't update an unmounted component with mention of a no-op.  I noticed that the ondoubleclick event defaults to `noop` for pointed annotations.  Our preference is that nothing happens when our features are double-clicked.  Any thoughts (or questions)?

**Comment by ericsturman** [comment]
@tnrich I did some further investigation and found the issue (we were writing an array to the notes field in the feature).  It would be great if we could have a `featureDoubleClickedOverride` hook that would allow us to inspect the event/props and prevent the popup when clicking one of our features and pass through (by returning false) when a standard OVE feature is double clicked.

**Comment by tnrich** [comment]
@ericsturman I think that sounds reasonable. Can you make a separate issue for adding doubleClickOverrides to the repo?

Also, would you mind trying to PR that change to this repo? Should be fairly straightforward I believe. You can essentially do the same thing we're doing with the click handler overrides for features/parts/etc. 

Lemme know. Thanks!

**Comment by ericsturman** [comment]
@tnrich yes on both.
