### ISSUE TITLE
Add featureDoubleClickedOverride hook for custom behavior for different feature types

### ISSUE THREAD

**Issue by ericsturman** [TeselaGen/tg-oss#96]
@tnrich It would be great if we could have a `featureDoubleClickedOverride` hook that would allow us to inspect the event/props and prevent the edit feature dialog when double clicking one of our custom feature types and pass through (by returning false) when a standard OVE feature is double clicked allowing the edit feature dialog to display.

**Comment by tnrich** [comment]
Published a new version for ya @ericsturman !
